site_name: Changda Ma
site_url: https://changdama.github.io
site_description: Research in Architecture, Acoustics, and AI

theme:
  name: material
  logo: assets/profile.jpg
  features:
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to system preference
  icon:
    logo: material/library

plugins:
  - search

nav:
  - Home: index.md

  - Music Technology:
      - Overview: projects/music_tech/index.md
      - Interactive Sound, XR Experience and Spatial audio:
          - Noise & Sleep Disturbance: projects/noise-sleep.md
          - MusicGen-Rhythm: projects/musicgen-rhythm.md
          - COSMIC PULSES: projects/music_tech/COSMIC_PULSES.md
      - AI for Music:
          - MusicGen-Rhythm: projects/music_tech/musicgen_rhythm.md
          - Project B: projects/25-sp-project-b.md
      - Music Information Retrieval:
          - Project A: projects/25-sp-project-a.md
          - Project B: projects/25-sp-project-b.md
      - Music Symbolic and Perception:
          - Exploring the Influence of Syncopation and Loudness on Listener Arousal in Music: projects/music_tech/Syncopation.md
      - Sonification:
          - Project A: projects/25-sp-project-a.md    
      - Acoustics:
          - Project A: projects/25-sp-project-a.md

  - Audio Mixing and Recordings:
      - Overview: projects/Audio_Mixing_and_Recordings/index.md
      - Audio One- "What's Life": projects/noise-sleep.md
      - Audio Two- "Ethnic Fusion Elegy": projects/musicgen-rhythm.md
      - Audio Three- "Fibonacci Future Bass": projects/Audio_Mixing_and_Recordings/FFB.md



  - Architecture and Urban Technology:
      - Overview: projects/architecture/index.md
      - High Performance Buildings:
          - Noise & Sleep Disturbance: projects/noise-sleep.md
          - MusicGen-Rhythm: projects/musicgen-rhythm.md
          - XR Instruments: projects/xr-instruments.md
      - AI for Built Environment:
          - Project A: projects/25-sp-project-a.md
          - Project B: projects/25-sp-project-b.md
      - Built Environment and Health:
          - Project A: projects/25-sp-project-a.md
          - Project B: projects/25-sp-project-b.md
      - Digital Fabrication and Robotics:
          - Project A: projects/25-sp-project-a.md
          - Project B: projects/25-sp-project-b.md
      - Computational Design:
          - Project A: projects/25-sp-project-a.md
          - Project B: projects/25-sp-project-b.md
          
  - Spatial Analytics:
      - Overview: projects/spatial_analytics/index.md
      - GIS:
          - Project A: projects/25-sp-project-a.md
          - Project B: projects/25-sp-project-b.md
      - Spatial Regression:
          - Project A: projects/25-sp-project-a.md
          - Project B: projects/25-sp-project-b.md
      - GeoAI:
          - Project A: projects/25-sp-project-a.md
          - Project B: projects/25-sp-project-b.md  

  - Publications: publications.md
  - Design: Design.md
  - CV: cv.md
  - Contact: contact.md


markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/changdama
    - icon: fontawesome/brands/google-scholar
      link: https://scholar.google.com/citations?user=YourProfileID&user=NU5McRIAAAAJ
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/changda-ma-419601256/
    - icon: fontawesome/solid/envelope
      link: mailto:cma326@gatech.edu
    - icon: fontawesome/brands/orcid
      link: https://orcid.org/0009-0005-9355-8525
    - icon: fontawesome/brands/researchgate
      link: https://www.researchgate.net/profile/Changda-Ma/research

extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/site.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


